### ISSUE TITLE
GLM breaks when data is exactly linear

### ISSUE THREAD

**Issue by alanedelman** [JuliaStats/GLM.jl#117]
Take any exactly linear data and feed it to GLM
(arguably not the right function when you know the data is linear)

```
x=[1,2,3,4]
y=[24,34,44,54]
data=DataFrame(X=x,Y=y)
```

```
OLS = glm(Y~X, data, Normal(), IdentityLink())
```

anyway one gets the complaint

```
failure to converge in 30 iterations
```

which seems unfortunate.

**Comment by andreasnoack** [comment]
The stopping criterion produces `NaN`s for a perfect fit because it tests the relative change in the deviance (which is zero for a perfect fit). There are several ways we could fix this, e.g. by checking for `NaN`, but we could also change the stopping criterion. I've made a brief survey of major statistical packages

- R, as mentioned by @simonster in https://github.com/JuliaStats/GLM.jl/issues/105, uses a slight modification of the absolute value of the relative change in the deviance.
- SAS supports four different criteria: absolute change in deviance, relative change in deviance, length of gradient measured in the norm defined by the information matrix divided by the log-likelihood (**the default**), relative change in parameter values unless they are close to zero where the absolute change is used. All four methods add a small constant to the denominator similarly to R, but much smaller (1e-6).
- STATA uses a combination of the length of the gradient and either the relative change of the parameter values (**the default**) or the relative change to the log-likelihood.

I think we should consider using the absolute change in the deviance instead of the relative change because it's the absolute distance between deviances that is relevant when testing models. Most authors are quite vague about stopping criterion, but https://www.stat.wisc.edu/courses/st771-newton/papers/green.pdf supports my suggestion.

Alternatively, I'll just add a check for `NaN` to fix this issue.
