### ISSUE TITLE
Export fewer functions?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/GLM.jl#168]
I was wondering if we should stop exporting
- `delbeta!`
- `linpred!`
- `mueta`
- `mustart`
- `updateμ! `
- `wrkresp`

since they mainly seem relevant for developers.

**Comment by andreasnoack** [comment]
@palday Why are you closing all the issues? Please leave a comment for the motivation when doing so.

**Comment by palday** [comment]
These functions are no longer exported, so the issue is resolved. 

On issues that required information to be resolved, I've commented before closing. For very old issues where the issue is no longer relevant (e.g. singularities from collinearity predating the handling of rank deficiency), I've simply closed.

**Comment by andreasnoack** [comment]
> For very old issues where the issue is no longer relevant (e.g. singularities from collinearity predating the handling of rank deficiency), I've simply closed.

That's fine but please just state that in a comment such that it's clear to everybody.
