### ISSUE TITLE
Support for Negative Binomial Regression

### ISSUE THREAD

**Issue by DoktorMike** [JuliaStats/GLM.jl#209]
It would be great if GLM also supported Negative Binomial Regression Models. This could be implemented in a number of ways. An over/under dispersed Poisson is one way. In R this corresponds to selecting the "quasipoisson" family in the call to glm.

Any plans to include it? 

Happy to elaborate if necessary.

**Comment by nalimilan** [comment]
AFAIK quasi-poisson is completely different from negative binomial, even though these are often used in similar contexts. Implementation-wise, it seems that this package could support quasi-poisson, but fitting a negative binomial requires slightly different algorithms (in R, they are implemented in separate packages).

@dmbates must have thought about this already.

**Comment by dmbates** [comment]
For the most part I prefer to stay away from quasi-Poisson and negative binomial regression models but that may be because I don't know enough about them or the general problem of over-dispersion.

Of the two approaches I prefer negative binomial but only because the quasi-Poisson approach of "let's model the probability distribution of the response as a function which isn't a probability distribution" offends my sensibilities.  (I'm a recovering mathematician.)

Someone could probably read section 7.4 of "Modern Applied Statistics with S, 4th ed." and figure out what should happen.  Apparently one sets a parameter, called "theta" in the 'negative.binomial' family in the MASS package for R, to a fixed value, fits a Poisson-like GLM conditional on that value, evaluates a likelihood then optimizes with respect to theta.  I can't remember offhand what 'theta' represents in terms of the probability of success and number of successes in a Bernoulli process.  Perhaps @bbolker can help.  He knows more about this than I do.

**Comment by bbolker** [comment]
I agree with Doug in preferring explicit statistical models to quasi-likelihood, but I don't consider quasi-likelihood evil.

(1) "quasi-Poisson" doesn't really involve any different computation from the regular Poisson: the procedure is

- fit the Poisson model
- estimate the overdispersion, typically by dividing the deviance by the residual degrees of freedom (there's a bunch in McCullagh and Nelder about various ways to estimate overdispersion, e.g. putting residual deviance vs. Pearson chi-square statistics vs ... in the numerator)
- scale the estimated variance-covariance matrix of the parameters by the overdispersion
- compute standard errors, p-values, etc. as usual

(2) Doug is correct that if you have GLM machinery working, the way to estimate the negative binomial model is to optimize over the 'theta' parameter. The reason this works is that the negative binomial distribution *with a known theta parameter* falls in the exponential family, which means that standard GLM-fitting techniques such as IRLS will work fine.

In terms of the 'coin-flipping' definition of the negative binomial (distribution of number of Bernoulli trials until x successes occur), the 'theta' parameter is the number of successes (it's called 'size' in the MASS function): theta=1 corresponds to geometric, theta->infinity corresponds to Poisson (provided you scale the mean appropriately). However, for practical purposes you want to allow fractional values of this parameter, at which point the coin-flipping definition doesn't actually make much sense ... OTOH I'm not sure you really need to know that - all you really need is the pieces necessary for the negative binomial family with a fixed overdispersion parameter (i.e., mean-variance relationship and all of the stuff about the link function) and a sensible way to optimize over theta.  MASS's algorithm seems pretty good, although I have encountered problems where it's fragile.

It's nice to be able to fit alternative parameterizations of the negative binomial (e.g. a parameterization where theta varies with the mean such that the variance is proportional to the mean rather than equal to mu*(1+mu/theta)) , but then you have to move to a fully likelihood-based/nonlinear-optimization machine -- you can't just build on top of the GLM/IRLS framework.

**Comment by bbolker** [comment]
PS If you want a model family that is both parametric and includes both over- and underdispersion, then you need something like the COM-Poisson distribution (which *definitely* needs a general likelihood/nonlinear optimization framework)

**Comment by hung-q-ngo** [comment]
FYI: the above PR is an attempt to implement MASS's algorithm to estimate theta. The algorithm is exactly Newton-Raphson. 
```
MASS's algorithm seems pretty good, although I have encountered problems where it's fragile.
```
@bbolker : do you have some dataset where the algorithm is fragile ? In which way is it fragile?

**Comment by bbolker** [comment]
One common situation is when the data set is approximately Poisson (or even underdispersed), and the dispersion parameter becomes very large. I think I've also seen problems where people have tried to use very differently scaled parameters.

Here are some examples:

- https://stackoverflow.com/questions/11749977/why-does-glm-nb-throw-a-missing-value-error-only-on-very-specific-inputs/11751740#11751740
- https://stackoverflow.com/questions/40191202/nans-produced-in-negative-binomial-regression-when-using-dnbinom/40197568#40197568
- https://stat.ethz.ch/pipermail/r-help/2012-April/309878.html

**Comment by sanderdevries** [comment]
Hi all. Thanks for all the useful comments. I am currently using the negative binomial regression quite often, but unsatisfied with the goodness of fit statistics available. I have been looking into suitable definitions of pseudo-R-squared metrics for negative binomial regression. Cameron and Windmeijer (1995) propose an R-squared based on the deviance of the saturated and fitted model.  Specifically, they require the dispersion parameter of the saturated model to be equal to the dispersion parameter of the fitted model. The standard glm.nb package does not allow to fit a model in which the dispersion parameter (size) is fixed. Is there any way to work around this without having to calibrate a saturated model manually by optimizing the log likelihood function for fixed theta? Or alternatively, is there any other suitable and convenient goodness of fit metric available for a negative binomial model?

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
