### ISSUE TITLE
Improve error message in conversion to GLM.LmResp

### ISSUE THREAD

**Issue by miguelmorin** [JuliaStats/GLM.jl#239]
The following code (code snippet 1):
```
using DataFrames
using GLM

df = DataFrame(response = Number[])
for i in 1:10
    df = vcat(df, DataFrame(response = rand()))
end

fit(LinearModel, @formula(response ~ 1), df)
```
returns a cryptic error:
```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Number,1} to an object of type GLM.LmResp
```

But changing the initial type from `Number` to `Real` (code snippet 2):
```
using DataFrames
using GLM

df = DataFrame(response = Real[])
for i in 1:10
    df = vcat(df, DataFrame(response = rand()))
end

fit(LinearModel, @formula(response ~ 1), df)
```
gives a more helpful message:
```
ERROR: LoadError: `float` not defined on abstractly-typed arrays; please convert to a more specific type
```

And declaring as `Number` and then converting to `Real` works without a glitch (code snippet 3):
```
using DataFrames
using GLM

df = DataFrame(response = Number[])
for i in 1:10
    df = vcat(df, DataFrame(response = rand()))
end

df2 = DataFrame(response = map(Real, df[:response]))

fit(LinearModel, @formula(response ~ 1), df2)
```

This works because Julia converts to Float64.

Can GLM improve the error message in code snippet 1 to say that the type should be more specific? And can GLM make code snippet 2 use the same conversion as code snippet 3?

(I posted a version of this on [StackOverflow](https://stackoverflow.com/questions/50874295/julia-cannot-convert-an-object-of-type-arraynumber-1-to-an-object-of-type-g/50874297#50874297).)

**Comment by nalimilan** [comment]
How did you end up with an `Array{Number,1}` object? That sounds quite unusual, given that only `Real` values make sense for GLMs. The error you get from snippet 1 is due to the fact that since GLMs need `Real` values, we require `Array{<:Real}` inputs, so there is no `convert` method for `Array{Number,1}`. I guess we could add a method taking any `AbstractArray` which would call `convert(Array{Real,1}, a)`, but doing that only to improve the error message sounds a bit excessive.

The more fundamental problem is that it's hard to do the conversion to a concrete type automatically because the type to use cannot always be determined: for example, `map(Real, Number[1.0, big(2)])` still returns an `Array{Real}`. Maybe `float` should be improved in Base to support abstract types and use `promote_type` to choose the best element type.

**Comment by miguelmorin** [comment]
It was a lapse as a new user: I declared `Number` at the top of the snippet 1.

If GLM requires `Array{<:Real}` inputs, how come code snippet 2 fails?

**Comment by nalimilan** [comment]
It's due how `float` works, that's an issue in Julia Base.

**Comment by miguelmorin** [comment]
OK, I'll close this issue. If other people face the same problem, it is now documented with a solution.
