### ISSUE TITLE
Tests currently failing

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/GLM.jl#322]
There seems to be an issue somehow related to CSV. See https://travis-ci.org/JuliaStats/GLM.jl/jobs/561284900. This can probably be fixed by allowing more recent version in compat but it still shouldn't fail.

cc @quinnj

**Comment by quinnj** [comment]
The 0.4 release is pretty old at this point; pre-Project.toml files even. So for that release, CSV.jl didn't have Parsers.jl in it's explicit dependencies (hence the warning), but it also is trying to use an older API of Parsers.jl that doesn't exist, since 0.3.6 gets installed (which is the current, latest version). So yeah, the best solution is to just bump the CSV.jl requirement; I can make a quick PR.

**Comment by andreasnoack** [comment]
Fixed by #323.
