### ISSUE TITLE
Feature request: multinomial logistic regression

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaStats/GLM.jl#363]
Are there any plans to implement multinomial logistic regression?

Specifically, I am referring to the situation of a categorical output variable that has strictly greater than two possible classes. The classes are **not** ordered.

**Comment by DilumAluthge** [comment]
It looks like @ Nosferican has implemented this in [Econometrics.jl](https://github.com/Nosferican/Econometrics.jl). Would it be possible to merge some of that work into GLM.jl?

**Comment by DilumAluthge** [comment]
It looks like @Nosferican has implemented this in [Econometrics.jl](https://github.com/Nosferican/Econometrics.jl). Would it be possible to merge some of that work into GLM.jl?

**Comment by Nosferican** [comment]
It would require to change a few of the internals though. The way I fit it in Econometrics is through a vector generalized linear model. It would require the internals to allow for vector responses rather than a single response vector. I believe that is the biggest change. In terms of outputs, the parameters are per response so it would have `response_predictor`.

**Comment by jbrea** [comment]
I'd also be interested in this feature.

**Comment by andreasnoack** [comment]
Dup of https://github.com/JuliaStats/GLM.jl/issues/206
