### ISSUE TITLE
Potentially unclear documentation for categorical variables

### ISSUE THREAD

**Issue by alexboche** [JuliaStats/GLM.jl#407]
I had a data frame with variables `y,x1,x2,...,xn`, where `x1` is an `int` variable that takes several possible values. I wanted to regress `y` on `x2`, `x3`, and categorical dummies for all possible values of `x1`. 

If I'm not mistaken, I eventually found that the correct way to do this is:
```
GLM.lm( @formula(y ~ x1 + x2 + x3), df), contrasts = Dict(:x1 => DummyCoding()))
```

However, when I read the [documentation](https://juliastats.org/GLM.jl/stable/manual/#Categorical-variables-1), the first thing I tried was something like (ignore the fact that I don't really understand `transform`):
 ```
transform!(df, :region => (x -> categorical(x)) );
GLM.lm( @formula(y ~ x1 + x2 + x3), df))
```
I don't know what this did but it didn't appear to change the regression output. 

A stack exchange post also suggested using the `pool!` function but my Julia didn't seem to know what that was.

I'm just telling you my experience finding this a little unclear. I a total noobie but that gives me insights into what that's like which advanced users might lack. Hope this is useful.

**Comment by nalimilan** [comment]
Yes docs needs to be improved, but we're already aware of that. We just lack people to work on it.

FWIW, your `transform!` call cannot have any effect since it doesn't change any of the `x*` variables. You'd need something like `transform!(df, :x1 => categorical, :x2 => categorical, :x3 => categorical, renamecols=false)` or just `transform!(df, names(df, r"^x") .=> categorical, renamecols=false)`. This is documented in the DataFrames manual: https://dataframes.juliadata.org/stable/

**Comment by alexboche** [comment]
Thank you.
